-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clients
(
    client_id integer NOT NULL DEFAULT nextval('clients_client_id_seq'::regclass),
    client_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    age integer NOT NULL,
    weight integer NOT NULL,
    height integer NOT NULL,
    personal integer,
    appointment timestamp without time zone,
    CONSTRAINT clients_pkey PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS public.exercise
(
    exercise_id integer NOT NULL DEFAULT nextval('exercise_exercise_id_seq'::regclass),
    workout_id integer NOT NULL,
    exercise_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    weight integer NOT NULL,
    sets integer NOT NULL,
    repetition integer NOT NULL,
    CONSTRAINT exercise_pkey PRIMARY KEY (exercise_id)
);

CREATE TABLE IF NOT EXISTS public.gym
(
    gym_id integer NOT NULL DEFAULT nextval('gym_gym_id_seq'::regclass),
    gym_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    addres character varying(40) COLLATE pg_catalog."default" NOT NULL,
    opening_time timestamp without time zone NOT NULL,
    closing_time timestamp without time zone NOT NULL,
    fee integer NOT NULL,
    CONSTRAINT gym_pkey PRIMARY KEY (gym_id)
);

CREATE TABLE IF NOT EXISTS public.personals
(
    trainer_id integer NOT NULL DEFAULT nextval('personals_trainer_id_seq'::regclass),
    trainer_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    price integer NOT NULL,
    linked_gym integer NOT NULL,
    client_id integer,
    schedule json NOT NULL,
    CONSTRAINT personals_pkey PRIMARY KEY (trainer_id)
);

CREATE TABLE IF NOT EXISTS public.venenos
(
    id integer NOT NULL DEFAULT nextval('venenos_id_seq'::regclass),
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    price double precision NOT NULL,
    seller integer,
    quantity integer,
    CONSTRAINT venenos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.workout
(
    workout_id integer NOT NULL DEFAULT nextval('workout_workout_id_seq'::regclass),
    client_id integer NOT NULL,
    personal_id integer NOT NULL,
    workout_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    exercises_list text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT workout_pkey PRIMARY KEY (workout_id)
);

ALTER TABLE IF EXISTS public.clients
    ADD CONSTRAINT personal FOREIGN KEY (personal)
    REFERENCES public.personals (trainer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.personals
    ADD CONSTRAINT linkedgym FOREIGN KEY (linked_gym)
    REFERENCES public.gym (gym_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.venenos
    ADD CONSTRAINT "Seller" FOREIGN KEY (seller)
    REFERENCES public.personals (trainer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "fki_Seller"
    ON public.venenos(seller);

END;